mysite/myapp/urls.py
from django.urls import path
from myapp.views import (
    index,
    add_item,
    update_item,
    delete_item,
    ProductListView,
    ProductDetailView,
    ProductDeleteView,
    PaymentSuccessView,
    PaymentFailedView,
    create_checkout_session
)

app_name = "myapp"

urlpatterns = [
    # http://127.0.0.1:8000/myapp/
    path("", index, name='index'),
    # path("", ProductListView.as_view(), name="index"),
    path("<int:pk>/", ProductDetailView.as_view(), name="detail"),
    # http://127.0.0.1:8000/myapp/
    path("additem/", add_item, name="add_item"),
    path("updateitem/<int:my_id>/", update_item, name="update_item"),
    path("deleteitem/<int:pk>/", ProductDeleteView.as_view(), name="delete_item"),
    path("success/", PaymentSuccessView.as_view(), name="success"),
    path("failed/", PaymentFailedView.as_view(), name="failed"),
    path("api/checkout-session/<int:id>/", create_checkout_session, name="api_checkout_session"),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path("myapp/", include("myapp.urls", namespace='myapp')),
    path("users/", include("users.urls", namespace='users')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/users/urls.py
from django.urls import path
from .views import register, profile, seller_profile
from django.contrib.auth.views import LoginView, LogoutView

app_name = 'users'

urlpatterns = [
    #http://127.0.0.1:8000/users/
    path('register/', register, name='register'),
    path('login/', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('profile/', profile, name='profile'),
    path('sellerprofile/<int:id>/', seller_profile, name='sellerprofile'),
    ]

mysite/myapp/models.py
from django.db import models
from django.contrib.auth.models import User


class Product(models.Model):
    seller = models.ForeignKey(User, on_delete=models.CASCADE, default='8')
    name = models.CharField(max_length=100)
    price = models.IntegerField()
    description = models.CharField(max_length=200)
    image = models.ImageField(blank=True, upload_to='images')

    def __str__(self):
        return self.name

class OrderDetail(models.Model):
    customer_username = models.CharField(max_length=200)
    product = models.ForeignKey(Product, on_delete=models.PROTECT)
    amount = models.IntegerField(null=True)
    stripe_payment_intent = models.CharField(max_length=200, null=True)
    has_paid = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

mysite/myapp/views.py
import json
import stripe

from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.http import HttpResponseNotFound, JsonResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse, reverse_lazy
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import DetailView, ListView, TemplateView
from django.views.generic.edit import DeleteView

from .models import Product, OrderDetail


def index(request):
    page_obj = items = Product.objects.all()

    item_name = request.GET.get("search")
    if item_name != "" and item_name is not None:
        page_obj = items.filter(name__icontains=item_name)

    paginator = Paginator(page_obj, 2)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    context = {"page_obj": page_obj}
    return render(request, "myapp/index.html", context)


class ProductListView(ListView):
    model = Product
    template_name = "myapp/index.html"
    context_object_name = "items"
    paginate_by = 2


# def indexItem(request, my_id):
#     item = Product.objects.get(id=my_id)
#     context = {"item": item}
#     return render(request, "myapp/detail.html", context=context)


class ProductDetailView(DetailView):
    model = Product
    template_name = "myapp/detail.html"
    context_object_name = "item"
    pk_url_kwarg = "pk"

    def get_context_data(self, **kwargs):
        context = super(ProductDetailView, self).get_context_data(**kwargs)
        context["stripe_publishable_key"] = settings.STRIPE_PUBLISHABLE_KEY
        return context


@login_required
def add_item(request):
    if request.method == "POST":
        name = request.POST.get("name")
        price = request.POST.get("price")
        description = request.POST.get("description")
        image = request.FILES["upload"]
        seller = request.user
        item = Product(
            name=name, price=price, description=description, image=image, seller=seller
        )
        item.save()
    return render(request, "myapp/additem.html")


def update_item(request, my_id):
    item = Product.objects.get(id=my_id)
    if request.method == "POST":
        item.name = request.POST.get("name")
        item.price = request.POST.get("price")
        item.description = request.POST.get("description")
        item.image = request.FILES.get("upload", item.image)
        item.save()
        return redirect("/myapp/")
    context = {"item": item}
    return render(request, "myapp/updateitem.html", context)


def delete_item(request, my_id):
    item = Product.objects.get(id=my_id)
    if request.method == "POST":
        item.delete()
        return redirect("/myapp/")
    context = {"item": item}
    return render(request, "myapp/deleteitem.html", context)


class ProductDeleteView(DeleteView):
    model = Product
    success_url = reverse_lazy("myapp:index")


@csrf_exempt
def create_checkout_session(request, id):
    product = get_object_or_404(Product, pk=id)

    stripe.api_key = settings.STRIPE_SECRET_KEY
    checkout_session = stripe.checkout.Session.create(
        payment_method_types=["card"],
        line_items=[
            {
                "price_data": {
                    "currency": "usd",
                    "product_data": {
                        "name": product.name,
                    },
                    "unit_amount": int(product.price * 100),
                },
                "quantity": 1,
            }
        ],
        mode="payment",
        success_url=request.build_absolute_uri(reverse("myapp:success"))
        + "?session_id={CHECKOUT_SESSION_ID}",
        cancel_url=request.build_absolute_uri(reverse("myapp:failed")),
    )

    # OrderDetail.objects.create(
    #     customer_email=email,
    #     product=product, ......
    # )

    order = OrderDetail()
    order.product = product
    order.stripe_payment_intent = checkout_session["payment_intent"]
    order.amount = int(product.price * 100)
    order.save()

    # return JsonResponse({'data': checkout_session})
    return JsonResponse({"sessionId": checkout_session.id})


class PaymentSuccessView(TemplateView):
    template_name = "myapp/payment_success.html"

    def get(self, request, *args, **kwargs):
        session_id = request.GET.get("session_id")
        if session_id is None:
            return HttpResponseNotFound()

        stripe.api_key = settings.STRIPE_SECRET_KEY
        session = stripe.checkout.Session.retrieve(session_id)

        order = get_object_or_404(
            OrderDetail, stripe_payment_intent=session.payment_intent
        )
        order.has_paid = True
        order.save()
        return render(request, self.template_name)


class PaymentFailedView(TemplateView):
    template_name = "myapp/payment_failed.html"

mysite/myapp/templates/myapp/additem.html
{% extends "myapp/base.html" %}

{% block content %}
<div class="ml-[200px]">
    <h1 class="text-2xl m-10 font-bold text-green-600"> Add New Item Below</h1>
    <form class="w-1/3 bg-white shadow-md m-10 px-8 py-8 " method="post" enctype="multipart/form-data">
    {% csrf_token %}
        <div class="mb-4 ">
            <label class="block text-gray-700 text-md font-bold mb-2" for="name">Item Name</label>
            <input class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700" type="text" placeholder="Name..." name="name" id="name">
            <label class="block text-gray-700 text-md font-bold mb-2 mt-2" for="price">Item Price</label>
            <input class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700" type="text" placeholder="Price..." name="price" id="price">
            <label class="block text-gray-700 text-md font-bold mb-2 mt-2" for="description">Item Description</label>
            <input class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700" type="text" placeholder="Description..." name="description" id="description">
            <input class="block mt-4" type="file" accept="image/*" name="upload" id="upload">
            <button class="block bg-green-600 text-white p-3 mt-4" type="submit" name="Add Item" value="Add Item">Add Item</button>
        </div>
    </form>
</div>

{% endblock content %}

mysite/myapp/templates/myapp/base.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href='{% static "myapp/src/output.css" %}'>
        <title>Doc</title>
    </head>
    <body>
        
        {% include "./navbar.html" %}

        {% block content %}
            
        {% endblock content %}
        
        {% comment %} <script src="" async defer></script> {% endcomment %}
    </body>
</html>

mysite/myapp/templates/myapp/contacts.html
<html>
    <head>
        
    </head>
    <body>
        <h1> This is contacts template</h1>
    </body>
</html>

mysite/myapp/templates/myapp/deleteitem.html
{% extends "myapp/base.html" %}

{% block content %}
<h1 class="text-2xl m-10 w-3/5 font-bold">Delete Product</h1>
<form class="bg-white shadow-md m-10 w-3/5 rounded px-8 pt-6 pb-8 mb-4" method="post">
    {% csrf_token %}
    <div>
        <label class="block text-gray text-sm font mb-2" >Are you sure you want to delete this item</label>
        <label class="block text-gray text-sm font mb-2" >{{item.name}}</label>
        <img class="w-40 h-40 mb-4" src="{{item.image.url}}" alt="">
    </div>
    <input class="bg-red-500 text-white px-5 py-2" type="submit" value="Confirm">
    <a class="button bg-green-500 text-white px-5 py-2 " href="{%url 'myapp:index'%}">Cancel</a>
</form>
{% endblock content %}

mysite/myapp/templates/myapp/detail.html
{% extends "myapp/base.html" %}
{% load humanize %}

{% block content %}
	<div class="flex p-10 w-full h-200">
		<img class="w-1/3" src="{{ item.image.url }}" alt="itemPhoto">
		<div class="w-2/3 text-xl ml-10 mt-5">
			<p class="mt-5">{{ item.name }}</p>
			<p class="mt-5 text-green-500">$ {{ item.price | intcomma }}</p>
			<p class="mt-5 text-gray-600">{{ item.description }}</p>
			<p class="mt-5 text-gray-600"><a href="{% url 'users:sellerprofile' item.seller.id %}">@{{ item.seller }}</a></p>
			<p class="mt-5 text-gray-600">{{ item.seller.profile.contact_number }}</p>
			<button class="bg-green-500 text-white mt-[50px]"><a href="{% url 'myapp:update_item' item.id %}">Update Item</a></button>
			<button class="bg-red-500 text-white mt-[50px]"><a href="{% url 'myapp:delete_item' item.id %}">Delete Item</a></button>
			<button class="bg-green-500 text-white mt-[50px]" id="checkout">Checkout</button>
		</div>
		
	</div>
	
	<script src="https://js.stripe.com/v3/"></script>
<script type="text/javascript">
    // Create an instance of the Stripe object with your publishable API key
    var stripe = Stripe('{{ stripe_publishable_key }}');
    var checkoutButton = document.getElementById('checkout');

    checkoutButton.addEventListener('click', function () {

        // Create a new Checkout Session using the server-side endpoint you
        // created in step 3.
        fetch("{% url 'myapp:api_checkout_session' id=item.id %}", {
            method: 'POST',
        })
            .then(function (response) {
                return response.json();
            })
            .then(function (session) {
                return stripe.redirectToCheckout({ sessionId: session.sessionId });
            })
            .then(function (result) {
                // If `redirectToCheckout` fails due to a browser or network
                // error, you should display the localized error message to your
                // customer using `error.message`.
                if (result.error) {
                    alert(result.error.message);
                }
            })
            .catch(function (error) {
                console.error('Error:', error);
            });
    });
</script>
{% endblock content %}

mysite/myapp/templates/myapp/index.html
{% extends "myapp/base.html" %}

{% block content %}
<main
  class="mt-10 mx-auto max-w-7xl px-4 sm: mt-12 sm: px-6 md: mt-16 lg: mt-20 lg: px-8 xl: mt-28"
>
  <div class="sm: text-center lg: text-left">
    <h1
      class="text-3xl font-extrabold text-gray-900 sm:text-4xl md:text-5xl text-center"
    >
      <span class="inline">Эксклюзивные товары</span>
      <span class="inline text-green-500">По Супер Ценам</span>
    </h1>
    <p
      class="mt-3 text-base text-gray-500 sm: mt-5 sm: text-lg sm: max-w-xl sm: mx-auto md: mt-5 md: text-xl lg: mx-0"
    >
      Вы можете заказать товар из любой точки мира. Доставка включена
    </p>
  </div>

    <div class="mt-5 p-10 justify-center">
        <h2>Search</h2>
        <form action="" method="get">
          <input type="text" name="search" id="">
        </form>
    </div>



  <div class="p-10 grid grid-cols-1 sm: grid-cols-1 md: grid-cols-3 xl: grid-col-3 lg: grid-col-3 gap-3">
    {%for item in page_obj%}
    <a href="{% url 'myapp:detail' item.id %}">
      <div class="rounded overflow-hidden shadow-lg">
        <img
          class="w-full h-[400px]"
          src="{{item.image.url}}"
          srcset="
            {{item.image.url}}?width=400 400w,
            {{item.image.url}}?width=800 800w
          "
          sizes="(max-width: 800px) 100vw, 50vw"
          loading="lazy"
        />
        <div class="px-6 py-4">
          <p class="font-bold text-xl mb-2">{{item.name}}</p>
          <p class="font-bold text-xl text-green-500 mb-2">$ {{item.price}}</p>
          <p class="font-bold text-xl text-indigo-500 mb-2">by: {{item.seller}}</p>
          <p class="text-gray-500 text-base">{{item.description}}</p>
        </div>
      </div>
    </a>
    
    {% endfor %}
  </div>

  <div>

    <span>
      {% if page_obj.has_previous %}
      <a href="?page=1">First</a>
      <a href="?page={{page_obj.previous_page_number}}">Previous</a>
      {% endif %}
    </span>
    <span>
      {{page_obj}}
    </span>
    <span>
      {% if page_obj.has_next %}
      <a href="?page={{page_obj.next_page_number}}">Next</a>
      <a href="?page={{page_obj.paginator.num_pages}}">Last</a>
      {% endif %}
    </span>
  </div>
</main>

{% endblock content %}

mysite/myapp/templates/myapp/navbar.html
{% load static %}

<nav class="bg-white shadow-lg">
    <div class="max-w-6xl mx-auto px-4">
        <div class="flex justify-between">
            <div class="flex spase-x-7">
                <div>
                    <a href="{%url 'myapp:index' %}" class="flex items-center px-2 py-4"> 
                    <img class="h-8 w-8" src='{% static "images/shop.png" %}' alt="logo" />
                    <span class="text-gray-500 font-semibold text-xl">Pro Shop</span> 
                </a>
                </div>
                <div class="items-center flex space-x-1"> 
                    <a href="{%url 'myapp:index' %}" class="py-4 px-2 text-gray-500 font-semibold border-b-4 border-green-500">Home</a>
                    <a href= "{%url 'myapp:add_item' %}" class="py-4 px-2 text-gray-500 font-semibold">Add Item</a>
                    <a href= "#" class="py-4 px-2 text-gray-500 font-semibold">Contacts</a>
                    {% if user.is_authenticated %}
                    <a class="py-4 px-2 text-gray-500 font-semibold" href="{% url 'users:logout' %}">Logout</a>
                    <a class="py-4 px-2 text-gray-500 font-semibold" href="{% url 'users:profile' %}">Profile</a>
                    {% else %}
                    <a class="py-4 px-2 text-gray-500 font-semibold" href="{% url 'users:login' %}">Login</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</nav>

mysite/myapp/templates/myapp/payment_failed.html
{% extends "myapp/base.html" %}

{% block content %}
    <p>Payment failed</p>
{% endblock content %}

mysite/myapp/templates/myapp/payment_success.html
{% extends "myapp/base.html" %}

{% block content %}
    <p>You have successfully paid</p>
{% endblock content %}

mysite/myapp/templates/myapp/product_confirm_delete.html
<form action="" method="post">
    {% csrf_token %}
    <p>Do you want to delete{{object}}</p>
    <input type="submit", value="Delete">
</form>

mysite/myapp/templates/myapp/updateitem.html
{% extends "myapp/base.html" %}

{% block content %}
<div class="ml-[200px]">
    <h1 class="text-2xl m-10 font-bold text-green-600"> Update New Item</h1>
    <form class="w-1/3 bg-white shadow-md m-10 px-8 py-8 " method="post" enctype="multipart/form-data">
    {% csrf_token %}
        <div class="mb-4 ">
            <label class="block text-gray-700 text-md font-bold mb-2" for="name">Item Name</label>
            <input class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700" value='{{item.name}}' type="text" placeholder="Name..." name="name" id="name">
            <label class="block text-gray-700 text-md font-bold mb-2 mt-2" for="price">Item Price</label>
            <input class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700"value='{{item.price}}' type="text" placeholder="Price..." name="price" id="price">
            <label class="block text-gray-700 text-md font-bold mb-2 mt-2" for="description">Item Description</label>
            <input class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700" value='{{item.description}}' type="text" placeholder="Description..." name="description" id="description">
            <img class="w-20, h-20" src="{{item.image.url}}" alt="">
            <input class="block mt-4" type="file" accept="image/*" name="upload" id="upload">
            <button class="block bg-green-600 text-white p-3 mt-4" type="submit" name="Add Item" value="Add Item">Update Item</button>
        </div>
    </form>
</div>

{% endblock content %}