mysite/myapp/urls.py
from django.urls import path
from myapp.views import (
    index,
    add_item,
    update_item,
    delete_item,
    ProductListView,
    ProductDetailView,
    ProductDeleteView,
    PaymentSuccessView,
    PaymentFailedView,
    create_checkout_session
)

app_name = "myapp"

urlpatterns = [
    # http://127.0.0.1:8000/myapp/
    path("", index, name='index'),
    # path("", ProductListView.as_view(), name="index"),
    path("<int:pk>/", ProductDetailView.as_view(), name="detail"),
    # http://127.0.0.1:8000/myapp/
    path("additem/", add_item, name="add_item"),
    path("updateitem/<int:my_id>/", update_item, name="update_item"),
    path("deleteitem/<int:pk>/", ProductDeleteView.as_view(), name="delete_item"),
    path("success/", PaymentSuccessView.as_view(), name="success"),
    path("failed/", PaymentFailedView.as_view(), name="failed"),
    path("api/checkout-session/<int:id>/", create_checkout_session, name="api_checkout_session"),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path("myapp/", include("myapp.urls", namespace='myapp')),
    path("users/", include("users.urls", namespace='users')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/users/urls.py
from django.urls import path
from .views import register, profile, seller_profile
from django.contrib.auth.views import LoginView, LogoutView

app_name = 'users'

urlpatterns = [
    #http://127.0.0.1:8000/users/
    path('register/', register, name='register'),
    path('login/', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('profile/', profile, name='profile'),
    path('sellerprofile/<int:id>/', seller_profile, name='sellerprofile'),
    ]

mysite/users/models.py
from django.db import models
from django.contrib.auth.models import User


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(blank=True, upload_to='_profile_images')
    contact_number = models.CharField(max_length=50, default='+79123456789')

    def __str__(self) -> str:
        return self.user.username

mysite/users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms



class NewUserForm(UserCreationForm):
    email = forms.EmailField(
        required=True, 
        widget=forms.EmailInput(
            attrs={"class":"focus:outline-none", 'placeholder':'mail@mail.com'}
            ),
        )
    username = forms.CharField(required=True, 
        widget=forms.TextInput(
            attrs={"class":"focus:outline-none", 'placeholder':'Enter username...'}
            ),
        )
    password1 = forms.CharField(required=True, 
        widget=forms.PasswordInput(
            attrs={"class":"focus:outline-none", 'placeholder':'Enter password'}
            ),
        )
    password2 = forms.CharField(required=True, 
        widget=forms.PasswordInput(
            attrs={"class":"focus:outline-none", 'placeholder':'Enter same password'}
            ),
        )

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')
    
    # def save(self, commit=True):
    #     user = super(NewUserForm, self).save(commit=False)
    #     user.email = self.cleaned_data['email']
    #     if commit:
    #         user.save()
    #     return user

mysite/users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from .forms import NewUserForm
from django.contrib.auth.decorators import login_required
from .models import Profile
from django.contrib.auth.models import User

def register(request):
    if request.method == 'POST':
        form = NewUserForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('myapp:index')
    form = NewUserForm()
    context={'form':form}
    return render(request, 'users/register.html', context)

@login_required
def profile(request):
    if request.method == 'POST':
        contact_number = request.POST.get('number')
        image = request.FILES("upload")
        user = request.user
        profile = Profile(user=user, contact_number=contact_number, image=image)
        profile.save()
    return render(request, 'users/profile.html')

def seller_profile(request, id):
    seller = User.objects.get(id=id)

    context = {'seller':seller}
    
    return render(request, 'users/sellerprofile.html', context)

mysite/users/templates/users/login.html
{% extends "myapp/base.html" %}

{% block content %}
<div class="container py-5">
    <h1 class="text-2xl m-10 font-bold">Login User</h1>
    <form class="w-2/5 bg-white-700 shadow-md m-10 rounded px-8 pt-6 pb-8 mb-4" method="post">
        {% csrf_token %}
        <div class="mb-2">
            <label class="block text-gray-700 text-sm font-bold mb-2">Username</label>
            <p class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700 leading-tight">{{form.username}}</p>
            <label class="block text-gray-700 text-sm font-bold mt-5 mb-2">Password</label>
            <p class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700 leading-tight">{{form.password}}</p>
        </div>
        <button class="bg-green-500 text-white px-5 py-2" type="submit">Login</button>
        <button class="bg-sky-600 text-white px-5 py-2"><a href="{% url 'users:register' %}">Register?</a></button>
    </form>
</div>
{% endblock content %}

mysite/users/templates/users/logout.html
{% extends "myapp/base.html" %}

{% block content %}
<h1>You have been logout</h1>
{% endblock content %}

mysite/users/templates/users/profile.html
{% extends "myapp/base.html" %}

{% block content %}

    {% if user.profile %}
    <div class="grid p-10 grid-cols-1 lg:grid-cols-3 sm:grid-cols-1">
        <div class="rounded shadow-lg">
            <div>
                {% if  user.profile.image %}
                    <img src="{{ user.profile.image.url }}">
                {% endif %}
                
            </div>
            <h1 class="font-bold text-xl m-2">{{ user.username }}</h1>
        </div>
    </div>
    {% else %}
    <div class="container py-5">
        <h1 class="text-2xl m-10 font-bold">Register User</h1>
        <form class="w-2/5 bg-white-700 shadow-md m-10 rounded px-8 pt-6 pb-8 mb-4" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="mb-2">
                <label class="block text-gray-700 text-sm font-bold mb-2">Upload profile image </label>
                <input class="block mt-4" type="file" accept="image/*" name="upload" id="upload" required>
                <label class="block text-gray-700 text-sm font-bold mt-5 mb-2">Contact number</label>
                <input class="block mt-4" type="text"  name="number" id="number">
            </div>
            <button class="bg-green-500 text-white px-5 py-2" type="submit">Create Profile</button>
        </form>
    </div>
    {% endif %}
   
{% endblock content %}

mysite/users/templates/users/register.html
{% extends "myapp/base.html" %}

{% block content %}

    <div class="container py-5">
        <h1 class="text-2xl m-10 font-bold">Register User</h1>
        <form class="w-2/5 bg-white-700 shadow-md m-10 rounded px-8 pt-6 pb-8 mb-4" method="post">
            {% csrf_token %}
            <div class="mb-2">
                <label class="block text-gray-700 text-sm font-bold mb-2">Username</label>
                <p class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700 leading-tight">{{form.username}}</p>
                <label class="block text-gray-700 text-sm font-bold mt-5 mb-2">Email</label>
                <p class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700 leading-tight">{{form.email}}</p>
                <label class="block text-gray-700 text-sm font-bold mt-5 mb-2">Password</label>
                <p class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700 leading-tight">{{form.password1}}</p>
                <label class="block text-gray-700 text-sm font-bold mt-5 mb-2">Confirm Password</label>
                <p class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700 leading-tight">{{form.password2}}</p>
            </div>
            <button class="bg-green-500 text-white px-5 py-2" type="submit">Register</button>
        </form>
    </div>

{% endblock content %}

mysite/users/templates/users/sellerprofile.html
{% extends "myapp/base.html" %}

{% block content %}
<div class="grid p-10 grid-cols-1 lg:grid-cols-3 sm:grid-cols-1">
    <div class="rounded shadow-lg">
        <div>
            {% if  user.profile.image %}
                <img src="{{ seller.profile.image.url }}">
            {% endif %}
            
        </div>
        <h1 class="font-bold text-xl m-2">{{ seller.username }}</h1>
    </div>
</div>
{% endblock content %}